import { useRef } from 'react'
import { Container } from '~/components/ui/Container'
import { Figure } from '~/components/ui/Figure'
import { SectionHeading } from '~/components/ui/SectionHeading'
import { useReveal } from '~/lib/motion'
import type { Guarantee } from '~/data/types'

/**
 * The dark right-rail "Guaranteed" panel is the one genuinely good thing
 * on the live site — six concrete commitments, stated plainly. It was
 * stuck in a 200px sidebar repeated on every page. Here it becomes a
 * real section, paid off by the platform story that makes the claims
 * credible.
 */
export function PlatformSection({ guarantees }: { guarantees: Guarantee[] }) {
  const ref = useRef<HTMLDivElement>(null)
  useReveal(ref)

  return (
    <section className="on-dark bg-navy-900 py-20 text-white lg:py-28">
      <Container>
        <div className="grid gap-12 lg:grid-cols-2 lg:gap-16 lg:items-start">
          <div>
            <SectionHeading
              tone="dark"
              lead="One platform underneath all of it."
              rest="That is why the price is fixed."
            />
            <div className="mt-6 space-y-4 text-lead text-white/80 max-w-[54ch]">
              <p>
                Every Arepo product is generated by the same Rapid Application
                Development tool — the Arepo Platform. It is how we deliver
                browser-based database solutions at a fraction of the time and
                cost normally associated with bespoke development.
              </p>
              <p>
                It also means the thing you buy is not frozen. When your
                business rules change, the application changes with them.
              </p>
            </div>
          </div>

          <Figure slot="home.platform" className="border border-white/10" />
        </div>

        <div ref={ref} className="mt-16 grid gap-10 sm:grid-cols-2 lg:grid-cols-3">
          {guarantees.map(guarantee => (
            <div key={guarantee.title} data-reveal className="border-t border-cyan-500/40 pt-4">
              <h3 className="text-h3 text-cyan-500">{guarantee.title}</h3>
              <p className="mt-2 text-base text-white/80">{guarantee.detail}</p>
            </div>
          ))}
        </div>
      </Container>
    </section>
  )
}
